# Site Information
site_name: test 0302
site_url: https://github.com/Harry-CunXiang/itaa-markdown.git
# site_description: test 0302

# # Repository Information
# repo_name: itaa-markdown
# repo_url: https://github.com/Harry-CunXiang/itaa-markdown.git
# edit_uri: 'edit/main/docs'
docs_dir: 'docs'
# # site_dir: 'site'
# remote_branch: 'gh-pages'
# remote_name: 'origin'

# Server info
# dev_addr: '127.0.0.1:8000'


nav:

  - Table of Content: 

    - 0. Information: index.md

    - 3. Requirement: 

      - 3.3 Non Functional Requirements: 

        - 'NFR1' : Non Functional Requirements/nonfunctionalrequirement_S1lzHYpaCo_ryd7nMQyh.md

        - 'NFR2' : Non Functional Requirements/nonfunctionalrequirement_HkASFaa0j_ryd7nMQyh.md

        - 'NFR3' : Non Functional Requirements/nonfunctionalrequirement_r1pUFa6Ri_ryd7nMQyh.md

        - 'NFR4' : Non Functional Requirements/nonfunctionalrequirement_SJeDDtpp0j_ryd7nMQyh.md

    - 5. Architecture: 

      - 5.1 Architecture Overview: 

        - 5.1.1 Services View: 

          - 'sv' : Services View/aodservices_3PjdKUI5Ww2_ryd7nMQyh.md

        - 5.1.2 Enterprise View: 

          - 'e1' : Enterprise View/aodenterprise_3PMFomeICa2.md

        - 5.1.3 IT System View: 

          - 'us2' : IT System View/aoditsystem_3PMFt2PKBKs.md

      - 5.3 Component Model: 

        - 5.3.1 Static View: 

          - 'stv' : Static View/cmstaticview_3Pjf4AbboFC_ryd7nMQyh.md

        - 5.3.2 Sequence View: 

          - 'sq' : Sequence View/cmdynamicview_3PMFBAB1MIs.md

      - 5.4 Operational Model: 

        - 5.4.1 Logical Operational View: 

          - 'lom' : Logical Operational View/lomview_3PjefcXEu1m_ryd7nMQyh.md

          - 'lom2' : Logical Operational View/lomview_3PMJF8xfpWm.md

        - 5.4.2 Prescribed Operational View: 

          - 'pom' : Prescribed Operational View/pomview_3Pjfn1OH3VB_ryd7nMQyh.md

    


markdown_extensions:

  - md_in_html

  - toc:

      permalink: True

  - footnotes

  - tables

  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - attr_list

plugins:
  - glightbox
  - search

theme:

  name: material
  palette:
    primary: 'black'
    accent: 'red'
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'
  logo: assets/ca.svg
  favicon: assets/ca.svg 
  features:
    # - navigation.tabs
    - navigation.tabs.sticky
  custom_dir:
    theme

extra_css:
  - extra.css
extra_javascript:
  - extra.js