# Site Information
site_name: Cognitive Architect v2022
site_url: https://github.com/Harry-CunXiang/itaa-markdown.git
# site_description: Cognitive Architect v2022

# # Repository Information
# repo_name: itaa-markdown
# repo_url: https://github.com/Harry-CunXiang/itaa-markdown.git
# edit_uri: 'edit/main/docs'
docs_dir: 'docs'
# # site_dir: 'site'
# remote_branch: 'gh-pages'
# remote_name: 'origin'

# Server info
# dev_addr: '127.0.0.1:8000'


nav:

  - Table of Content: 

    - 0. Information: index.md

    - 1. Overview: Overview.md

    - 2. Scope: 

      - 2.1 Business Challenge: Business-Challenge+'/'

    - 3. Requirement: 

      - 3.2 Functional Requirements: 

        - 'search &amp; a' : Functional-Requirements/search-&amp;-a+'/'

        - 'Search &amp; Recommendation' : Functional-Requirements/Search-&amp;-Recommendation+'/'

        - 'Compose Architecture' : Functional-Requirements/Compose-Architecture+'/'

        - 'Collaborate Architecture' : Functional-Requirements/Collaborate-Architecture+'/'

      - 3.3 Non Functional Requirements: 

        - 'System Availability' : Non-Functional-Requirements/System-Availability+'/'

        - 'System Security' : Non-Functional-Requirements/System-Security+'/'

        - 'System Scalablity' : Non-Functional-Requirements/System-Scalablity+'/'

        - 'User Expeirence - Channel' : Non-Functional-Requirements/User-Expeirence---Channel+'/'

        - 'Data Backup' : Non-Functional-Requirements/Data-Backup+'/'

        - 'System Performance' : Non-Functional-Requirements/System-Performance+'/'

        - 'System Maintainability' : Non-Functional-Requirements/System-Maintainability+'/'

    - 5. Architecture: 

      - 5.2 Architectural Decisions: 

        - 'Use Neo4j to store Architecture Data' : Architectural-Decisions/Use-Neo4j-to-store-Architecture-Data+'/'

        - 'Use MongoDB + Neo4J to store core repository information' : Architectural-Decisions/Use-MongoDB-+-Neo4J-to-store-core-repository-information+'/'

        - 'Core Repository use Excel format to load data' : Architectural-Decisions/Core-Repository-use-Excel-format-to-load-data+'/'

        - 'Use Loopback as API framework' : Architectural-Decisions/Use-Loopback-as-API-framework+'/'

        - 'Use MxGraph as drawing framework' : Architectural-Decisions/Use-MxGraph-as-drawing-framework+'/'

        - 'Use AngularJS 2 as the front-end framework' : Architectural-Decisions/Use-AngularJS-2-as-the-front-end-framework+'/'

        - 'Define the Architecture to be composed of a collection of abstract artifacts. The system also defines a &#34;changeable&#34; set of concrete artifact types allowing for evolution of the scope of content documented within an Architecture.' : Architectural-Decisions/Define-the-Architecture-to-be-composed-of-a-collection-of-abstract-artifacts.-The-system-also-defines-a-&#34;changeable&#34;-set-of-concrete-artifact-types-allowing-for-evolution-of-the-scope-of-content-documented-within-an-Architecture.+'/'

        - 'Use Neo4j Directly for Architecture &amp; Artifact Service' : Architectural-Decisions/Use-Neo4j-Directly-for-Architecture-&amp;-Artifact-Service+'/'

        - 'Involve Model Transformation for Graph Visualization &amp; Storage' : Architectural-Decisions/Involve-Model-Transformation-for-Graph-Visualization-&amp;-Storage+'/'

        - 'Which type of Cluster in IBM Cloud will be used for External Client?' : Architectural-Decisions/Which-type-of-Cluster-in-IBM-Cloud-will-be-used-for-External-Client?+'/'

        - 'Separate CAApp to CAWeb &amp; API Gateway &amp; Aggregate Service' : Architectural-Decisions/Separate-CAApp-to-CAWeb-&amp;-API-Gateway-&amp;-Aggregate-Service+'/'

        - 'Leverage IBM Cloud PV Encryption to support data encryption at-rest for external version' : Architectural-Decisions/Leverage-IBM-Cloud-PV-Encryption-to-support-data-encryption-at-rest-for-external-version+'/'

        - '2022 Infrastructure Migration' : Architectural-Decisions/2022-Infrastructure-Migration+'/'

        - 'Decouple CA frontend to multiple code repos' : Architectural-Decisions/Decouple-CA-frontend-to-multiple-code-repos+'/'

        - 'Use Webmaster as DNS Service' : Architectural-Decisions/Use-Webmaster-as-DNS-Service+'/'

        - 'Use BlueFringe to connect w3 network' : Architectural-Decisions/Use-BlueFringe-to-connect-w3-network+'/'

        - 'Use Instana as Monitor Tool' : Architectural-Decisions/Use-Instana-as-Monitor-Tool+'/'

        - 'Use LogDNA as Logging Service' : Architectural-Decisions/Use-LogDNA-as-Logging-Service+'/'

        - 'Use Classic OCP Cluster' : Architectural-Decisions/Use-Classic-OCP-Cluster+'/'

        - 'Use IBM SMTP server as Email Service' : Architectural-Decisions/Use-IBM-SMTP-server-as-Email-Service+'/'

        - 'Leverage OCP cronjob to implement CA&#39;s batch jobs' : Architectural-Decisions/Leverage-OCP-cronjob-to-implement-CA&#39;s-batch-jobs+'/'

        - 'Backup and restore' : Architectural-Decisions/Backup-and-restore+'/'

        - 'Production Maintenance' : Architectural-Decisions/Production-Maintenance+'/'

        - 'Use CAES DevOps Platform as well as the provides toolchains' : Architectural-Decisions/Use-CAES-DevOps-Platform-as-well-as-the-provides-toolchains+'/'

    - 6. RAID: 

      - 6.1 Risks: 

        - 'Risk-01 Neo4j Community Version Limitation' : Risks/Risk-01-Neo4j-Community-Version-Limitation+'/'

        - 'Risk-02 Instance Update Mechnism Limitation' : Risks/Risk-02-Instance-Update-Mechnism-Limitation+'/'

    - 11. Notes: 

      - 'Auto-Return Pen Design &amp; In-App Notification' : Notes/Auto-Return-Pen-Design-&amp;-In-App-Notification+'/'

      - 'Design for new &#34;Create&#34; elements mechanism' : Notes/Design-for-new-&#34;Create&#34;-elements-mechanism+'/'

      - 'Different Graph Database Comparison' : Notes/Different-Graph-Database-Comparison+'/'

      - 'GraphQL' : Notes/GraphQL+'/'

      - 'K8S PV Usage' : Notes/K8S-PV-Usage+'/'

      - 'Loopback 4' : Notes/Loopback-4+'/'

      - 'Offline Phase Two' : Notes/Offline-Phase-Two+'/'

      - 'Pass Pen System Map ' : Notes/Pass-Pen-System-Map-+'/'

      - 'ToC Template Configuration' : Notes/ToC-Template-Configuration+'/'

    


markdown_extensions:

  - md_in_html

  - toc:

      permalink: True

  - footnotes

  - tables

  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - attr_list

plugins:
  - glightbox
  - search

theme:

  name: material
  palette:
    primary: 'black'
    accent: 'red'
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'
  logo: assets/ca.svg
  favicon: assets/ca.svg 
  features:
    # - navigation.tabs
    - navigation.tabs.sticky
  custom_dir:
    theme

extra_css:
  - extra.css
extra_javascript:
  - extra.js